[project]
name = "vibecoding-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "fastapi>=0.120.1",
    "httpx>=0.28.1",
    "pydantic>=2.12.4",
    "uvicorn>=0.38.0",
]
